; Optional CLI upload: pio run -c platformio-ota.ini -e esp32-s3-pcb-ota -t upload
[platformio]
extra_configs = platformio.ini

[env:esp32-s3-pcb-ota]
extends = env:esp32-s3-pcb
upload_protocol = espota
upload_port = 192.168.4.1
extra_scripts =
    pre:scripts/wifi_include.py
    post:scripts/ota_upload.py
